runtime:
  log:
    failure_level: error

urls:
  latest_version_segment: latest
  latest_version_segment_strategy: redirect:to

antora:
  extensions:
  - require: '@antora/lunr-extension'

site:
  title: OpenDevStack
  start_page: opendevstack:getting-started:index.adoc
  url: https://www.opendevstack.org/ods-documentation

content:
  branches: master,1.*,2.*,3.*,4.*
  sources:
    - url: https://github.com/opendevstack/ods-core.git
      start_path: docs
      branches:
      - 1.2.x
      - 2.x
      - 3.x
      - 4.x
      - master
    - url: https://github.com/opendevstack/ods-jenkins-shared-library.git
      start_path: docs
      branches:
      - 1.2.x
      - 2.x
      - 3.x
      - 4.x
      - master
    - url: https://github.com/opendevstack/ods-provisioning-app.git
      start_path: docs
      branches:
      - 1.2.x
      - 2.x
      - 3.x
      - 4.x
      - master
    - url: https://github.com/opendevstack/ods-project-quickstarters.git
      start_path: docs
      branches:
      - 1.2.x
    - url: https://github.com/opendevstack/ods-quickstarters.git
      start_path: docs
      branches:
      - master
      - 2.x
      - 3.x
      - 4.x
output:
  dir: ./docs
ui:
  bundle:
    url: https://github.com/opendevstack/ods-docs-ui/releases/download/v2.0.0/ui-bundle.zip
